apiVersion: batch/v1
kind: Job
metadata:
  name: vprodb-init
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        args:
        - /bin/sh
        - -c
        - rm -rf /var/lib/mysql/lost+found
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-06ed8c2b8dae420a4
      restartPolicy: Never
