apiVersion: batch/v1
kind: Job
metadata:
  name: vprodb-init
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh", "-c", "until nslookup vprodb; do echo 'Waiting for vprodb'; sleep 2; done;"]
      restartPolicy: OnFailure
